# Generated by Django 3.1.7 on 2021-03-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharno', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='aadhar')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='location')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('currentdetails', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('truckno', models.CharField(blank=True, max_length=150, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='drivers')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.aadhar')),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='app.locations')),
            ],
        ),
    ]
