# Generated by Django 3.1.7 on 2021-03-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='price',
            field=models.FloatField(default=1123),
        ),
    ]
